set serveroutput on

INSERT INTO FORNECEDOR (N_FORNEC, NOME, ENDERECO, CPF, ESTRELA, DT_ATUALIZA, VENDA,COMISSAO)
VALUES(08492, 'Nelson de Sousa', 'Rua Madre Gomes', 45206587700, 5, sysdate, 40, 500.00); 

INSERT INTO FORNECEDOR (N_FORNEC, NOME, ENDERECO, CPF, ESTRELA, DT_ATUALIZA, VENDA,COMISSAO)
VALUES(08493, 'Juarez da Silva', 'Rua da Florida', 42988445700, 4, sysdate , 20, 200.00); 

select * from FORNECEDOR;
--DECLARE
--ATUALIZANDO DADOS DA TABELA FORNECEDOR
--ONDE ESTRELA É MAIOR OU IGUAL A 3
-- VALOR ADICIONADO A COMISSAO EM TEMPO DE EXECUÇÃO
BEGIN
  UPDATE FORNECEDOR
  SET COMISSAO=&valor
  WHERE ESTRELA >=3;
END;

BEGIN
  DELETE FROM FORNECEDOR
  WHERE N_FORNEC = &NUMERO_FORNECEDOR;
END;
